name: Deploy AcidTech Flask API to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: acidtech-prod-app
  AZURE_FUNCTIONAPP_NAME: acidtech-prod-api
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    name: Build and Deploy Flask API
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Flask tests (if any)
      run: |
        source venv/bin/activate
        # Add test commands here if tests exist
        echo "No tests configured yet"
    
    - name: Deploy Flask API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Deploy to Azure Function App (Optional)
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./api
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "🎉 Deployment successful!"
        echo "Frontend URL: https://acidtech-prod-app.azurewebsites.net"
        echo "API URL: https://acidtech-prod-api.azurewebsites.net"